POST https://lostminercommunity.onrender.com/api/auth/register/
Content-Type: application/json

{
  "username": "Nanda",
  "email": "lima.jefferson5286@gmail.com"
}

###
POST http://localhost:8000/api/auth/authorize/
Content-Type: application/json

{
  "code": "258760"
}

###
PUT http://localhost:8000/api/set_password/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb24iOjN9.nA3mbNA1NO_0g9vS35uPiPSvYbnzRfh8KuWBABVaDW8
Content-Type: application/json

{
  "password": "lá ele 4.0"
}

###
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "gameplayjubgamer@gmail.com"
}

###
PUT http://localhost:8000/api/refresh_token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb24iOjN9.nA3mbNA1NO_0g9vS35uPiPSvYbnzRfh8KuWBABVaDW8
