POST http://localhost:8000/api/register/
Content-Type: application/json

{
  "username": "jeffers",
  "email": "gameplayjubgamer@gmail.com"
}

###
POST http://localhost:8000/api/authorize/
Content-Type: application/json

{
  "code": "239623"
}

###
PUT http://localhost:8000/api/set_password/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb24iOjN9.nA3mbNA1NO_0g9vS35uPiPSvYbnzRfh8KuWBABVaDW8
Content-Type: application/json

{
  "password": "lá ele 4.0"
}

###
POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "email": "gameplayjubgamer@gmail.com",
  "password": "lá ele 4.0"
}

###
PUT http://localhost:8000/api/refresh_token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb24iOjN9.nA3mbNA1NO_0g9vS35uPiPSvYbnzRfh8KuWBABVaDW8
